name: Frontend

on:
  push:
  pull_request:
    paths:
      - ./frontend
    branches:
      - master
    tags-ignore:
      - "*.*"

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Setup dependencies
        run: |
          npm ci
        working-directory: ./frontend

      - name: Lint frontend
        run: |
          npm run lint
        working-directory: ./frontend

  unit-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 18.12.1
        uses: actions/checkout@v3
        with:
          node-version: "18.12.1"

      - name: Setup dependencies
        run: |
          npm ci
        working-directory: ./frontend

      - name: Unit test Frontend
        run: |
          npm run test
        working-directory: ./frontend
